{
  "hash": "901d715888ed8dd5187b62202f6c3d1b",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Two-Way ANOVA\"\nauthor: \"James Van Slyke\"\n---\n\n\n\n\n## Two-Way ANOVA\n\n*Before starting this section please review the section One-Way ANOVA first*\n\n### Revisiting One-Way ANOVA\n\nOne-way ANOVA is based on the general idea that the total variability $SS_T$ is partitioned (divided or separated) into two types of variability. The variability between the groups $SS_{between}$ and the variability within the groups $SS_{within}$. Remember that the variability between the groups needed to be *greater* than the variability within the groups because that would indicate that the difference between the groups was greater than the measurement error that existed within the groups.\n\n#### Main Effects\n\nTwo-way ANOVA goes beyond one-way ANOVA by analyzing the effects of two independent variables in the same experiment. In a two-way ANOVA the two independent variables are called *main effects* or *factors* and each main effect has its own individual hypothesis.\n\n#### Interaction effects\n\nFinally, the two-way ANOVA analyzes if there is an *interaction effect* between the two main effects or factors. An interaction effect occurs when the effect of one of the independent variables is not the same at all levels of the second independent variable. So the set up for a two-way ANOVA is:\n\n-   Independent variable 1 = Main effect 1 = Factor 1\n\n-   Independent variable 2 = Main effect 2 = Factor 2\n\n-   Interaction effect = Interaction between Factors 1 & 2\n\n#### Two-Way ANOVA Example\n\nThe example dataset tests what's called the \"beer googles effect\". Sometimes alcohol can have an effect on perceptions of attraction for potential dates, especially later in the evening at bars. The dataset tests whether perceptions of attractiveness change after drinking alcohol and whether males and females are effected by this phenomenon differently.\n\n##### Variables\n\nTwo Independent Variables (Main Effects or Factors)\n\n-   Main Effect 1 = Alcohol 3 Levels (None, 2 Pints, 4 Pints)\n-   Main Effect 2 = Gender 2 Levels (Male and Female)\n-   Interaction Effect = Gender x Alcohol\n-   DV = Attractiveness of the partner selected at the end of the evening\n\nAlternative Hypotheses\n\n-   $H_1$ Alcohol has an effect on the attractiveness level of the selected partner\n-   $H_2$ Gender has an effect on the attractiveness level of the partner.\n-   $H_3$ There is an interaction effect between Alcohol and Gender\n\nSum of Squares variation estimates\n\n### Fixing the Variables\n\nGet the dataset and import it\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(haven)\ngoggles <- read_sav(\"goggles.sav\")\n```\n:::\n\n\nCheck out Gender variable\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngoggles$Gender\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n<labelled<double>[48]>: Gender\n [1] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0\n[39] 0 0 0 0 0 0 0 0 0 0\n\nLabels:\n value  label\n     0   Male\n     1 Female\n```\n\n\n:::\n:::\n\n\nCheck out Alcohol variable\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngoggles$Alcohol\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n<labelled<double>[48]>: Alcohol Consumption\n [1] 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 1 1 1 1 1 1 1 1 2 2 2 2 2 2\n[39] 2 2 3 3 3 3 3 3 3 3\n\nLabels:\n value   label\n     1    None\n     2 2 Pints\n     3 4 Pints\n```\n\n\n:::\n:::\n\n\nCheck out Attractiveness variable\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngoggles$Attractiveness\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] 65 70 60 60 60 55 60 55 70 65 60 70 65 60 60 50 55 65 70 55 55 60 50 50 50\n[26] 55 80 65 70 75 75 65 45 60 85 65 70 70 80 60 30 30 30 55 35 20 45 40\nattr(,\"label\")\n[1] \"Attractiveness of Date\"\nattr(,\"format.spss\")\n[1] \"F8.0\"\nattr(,\"display_width\")\n[1] 13\n```\n\n\n:::\n:::\n\n\nAlcohol and Gender variables are factors. When they get imported from SPSS they don't function as well because the focus is on the numbers, not the labels or words.We can use tidyverse and the mutate function to fix this.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngoggles <- goggles %>% \n  mutate(Gender = factor(Gender, levels = c(0,1), \n         labels = c(\"Male\", \"Female\")))\n```\n:::\n\n\nWe can do the same thing with the Alcohol variable. Make sure you know the levels or numbering of the variable\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngoggles$Alcohol\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n<labelled<double>[48]>: Alcohol Consumption\n [1] 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 1 1 1 1 1 1 1 1 2 2 2 2 2 2\n[39] 2 2 3 3 3 3 3 3 3 3\n\nLabels:\n value   label\n     1    None\n     2 2 Pints\n     3 4 Pints\n```\n\n\n:::\n:::\n\n\nThen go ahead and mutate the variable as you did with Gender\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngoggles <- goggles %>% \n  mutate(Alcohol = factor(Alcohol, levels = c(1,2,3), \n            labels = c(\"None\", \"2 Pints\", \"4 Pints\")))\n```\n:::\n\n\n#### Running Two-Way ANOVA in R Studio\n\nNow we can move to the Two-Way ANOVA analysis. \"m3\" is the new object to save results so the formula will have this structure.\n\n> \\# m3 \\<- aov (this is the computation you are using, like t.test) Then the rest of your formula should look like this (Dependent variable \\~ Varible 1 + Variable 2 + Variable 1\\*Variable 2, data = \\[your dataset\\])\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm3 <- aov(Attractiveness ~ Gender + Alcohol + \n           Gender*Alcohol, data = goggles)\n```\n:::\n\n\nCheck the results\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(m3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               Df Sum Sq Mean Sq F value   Pr(>F)    \nGender          1    169   168.8   2.032    0.161    \nAlcohol         2   3332  1666.1  20.065 7.65e-07 ***\nGender:Alcohol  2   1978   989.1  11.911 7.99e-05 ***\nResiduals      42   3487    83.0                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nKey Findings from our output\\\nMain effect of Alcohol on attractiveness\\\nInteraction effect of Alcohol and Gender\\\n*What does this mean?*\n\n### Graphs for the Main Effects\n\nLet's use a graph to understand this better\\\nFirst let's look at each variable individually\n\n\n::: {.cell}\n\n```{.r .cell-code}\nGogglesAlcohol <- goggles %>%\n  group_by(Alcohol) %>%\n  summarize(n = n(),\n            mean = mean(Attractiveness),\n            sd = sd(Attractiveness),\n            se = sd/sqrt(n),\n            ci = qt(0.975, df = n - 1) * sd / sqrt(n))\n```\n:::\n\n\nGraph the Alcohol variable individually\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(GogglesAlcohol, aes(x = Alcohol,\n                                y = mean)) +\n  geom_point(size = 3) +\n  geom_line(size = 1) +\n  geom_errorbar(aes(ymin  =mean - ci, \n                    ymax = mean + ci), \n                width = .1)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.\nℹ Please use `linewidth` instead.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_line()`: Each group consists of only one observation.\nℹ Do you need to adjust the group aesthetic?\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Two-Way-ANOVA_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\nGraph the Gender variable individually\n\n\n::: {.cell}\n\n```{.r .cell-code}\nGogglesGender <- goggles %>%\n  group_by(Gender) %>%\n  summarize(n = n(),\n            mean = mean(Attractiveness),\n            sd = sd(Attractiveness),\n            se = sd/sqrt(n),\n            ci = qt(0.975, df = n - 1) * sd / sqrt(n))\n```\n:::\n\n\nGraph it\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(GogglesGender, aes(x = Gender,\n                           y = mean)) +\n  geom_point(size = 3) +\n  geom_line(size = 1) +\n  geom_errorbar(aes(ymin  =mean - ci, \n                    ymax = mean + ci), \n                width = .1) +\n  ylim(0,70)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_line()`: Each group consists of only one observation.\nℹ Do you need to adjust the group aesthetic?\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Two-Way-ANOVA_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\nGraph the Interaction Effect\n\nFinally, we can graph relationships for both variables.\\\nFirst find your descriptive statistics, but this time based on two independent variables\n\n\n::: {.cell}\n\n```{.r .cell-code}\nGogglesDescriptives <- goggles %>%\n  group_by(Alcohol, Gender) %>%\n  summarize(n = n(),\n            mean = mean(Attractiveness),\n            sd = sd(Attractiveness),\n            se = sd/sqrt(n),\n            ci = qt(0.975, df = n - 1) * sd / sqrt(n))\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`summarise()` has grouped output by 'Alcohol'. You can override using the\n`.groups` argument.\n```\n\n\n:::\n:::\n\n\nCheck it\n\n\n::: {.cell}\n\n```{.r .cell-code}\nGogglesDescriptives\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 7\n# Groups:   Alcohol [3]\n  Alcohol Gender     n  mean    sd    se    ci\n  <fct>   <fct>  <int> <dbl> <dbl> <dbl> <dbl>\n1 None    Male       8  66.9 10.3   3.65  8.64\n2 None    Female     8  60.6  4.96  1.75  4.14\n3 2 Pints Male       8  66.9 12.5   4.43 10.5 \n4 2 Pints Female     8  62.5  6.55  2.31  5.47\n5 4 Pints Male       8  35.6 10.8   3.83  9.06\n6 4 Pints Female     8  57.5  7.07  2.5   5.91\n```\n\n\n:::\n:::\n\n\nUse a line graph to graph the relationship\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(GogglesDescriptives, aes(x = Alcohol,\n                     y = mean, \n                     group=Gender, \n                     color=Gender)) +\n  geom_point(size = 3) +\n  geom_line(size = 1) +\n  geom_errorbar(aes(ymin  =mean - ci, \n                    ymax = mean + ci), \n                width = .1)\n```\n\n::: {.cell-output-display}\n![](Two-Way-ANOVA_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\nUse dodge functions to make graph clearer\n\n\n::: {.cell}\n\n```{.r .cell-code}\npd <- position_dodge(0.2)\nggplot(GogglesDescriptives, \n       aes(x = Alcohol, \n           y = mean, \n           group=Gender, \n           color=Gender)) +\n  geom_point(position = pd, \n             size = 3) +\n  geom_line(position = pd,\n            size = 1) +\n  geom_errorbar(aes(ymin = mean - ci, \n                    ymax = mean + ci), \n                width = .1, \n                position= pd)\n```\n\n::: {.cell-output-display}\n![](Two-Way-ANOVA_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\nAll the bells and whistles\n\n\n::: {.cell}\n\n```{.r .cell-code}\npd <- position_dodge(0.2)\nggplot(GogglesDescriptives, \n       aes(x = Alcohol, \n           y = mean, \n           group=Gender, \n           color=Gender)) +\n  geom_point(position=pd, \n             size = 3) +\n  geom_line(position = pd, \n            size = 1) +\n  geom_errorbar(aes(ymin = mean - ci, \n                    ymax = mean + ci), \n                width = .1, \n                position = pd, \n                size = 1) +\n  scale_color_brewer(palette=\"Set1\") +\n  theme_minimal() +\n  labs(title = \"Beer Goggels Effect\",\n       x = \"Amount of Alcohol Consumed\", \n       y = \"Mean Level of Attractiveness\",\n       color = \"Gender\")\n```\n\n::: {.cell-output-display}\n![](Two-Way-ANOVA_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n\nUse Tukey to look at specific differences in the groups you are interested in\n\n\n::: {.cell}\n\n```{.r .cell-code}\nTukeyHSD(m3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Tukey multiple comparisons of means\n    95% family-wise confidence level\n\nFit: aov(formula = Attractiveness ~ Gender + Alcohol + Gender * Alcohol, data = goggles)\n\n$Gender\n            diff       lwr      upr     p adj\nFemale-Male 3.75 -1.558607 9.058607 0.1613818\n\n$Alcohol\n                    diff        lwr        upr     p adj\n2 Pints-None      0.9375  -6.889643   8.764643 0.9544456\n4 Pints-None    -17.1875 -25.014643  -9.360357 0.0000105\n4 Pints-2 Pints -18.1250 -25.952143 -10.297857 0.0000040\n\n$`Gender:Alcohol`\n                                 diff        lwr        upr     p adj\nFemale:None-Male:None          -6.250 -19.851381   7.351381 0.7432243\nMale:2 Pints-Male:None          0.000 -13.601381  13.601381 1.0000000\nFemale:2 Pints-Male:None       -4.375 -17.976381   9.226381 0.9277939\nMale:4 Pints-Male:None        -31.250 -44.851381 -17.648619 0.0000003\nFemale:4 Pints-Male:None       -9.375 -22.976381   4.226381 0.3286654\nMale:2 Pints-Female:None        6.250  -7.351381  19.851381 0.7432243\nFemale:2 Pints-Female:None      1.875 -11.726381  15.476381 0.9983764\nMale:4 Pints-Female:None      -25.000 -38.601381 -11.398619 0.0000306\nFemale:4 Pints-Female:None     -3.125 -16.726381  10.476381 0.9825753\nFemale:2 Pints-Male:2 Pints    -4.375 -17.976381   9.226381 0.9277939\nMale:4 Pints-Male:2 Pints     -31.250 -44.851381 -17.648619 0.0000003\nFemale:4 Pints-Male:2 Pints    -9.375 -22.976381   4.226381 0.3286654\nMale:4 Pints-Female:2 Pints   -26.875 -40.476381 -13.273619 0.0000080\nFemale:4 Pints-Female:2 Pints  -5.000 -18.601381   8.601381 0.8796489\nFemale:4 Pints-Male:4 Pints    21.875   8.273619  35.476381 0.0002776\n```\n\n\n:::\n:::\n\n\nFor us, the most important difference is that males are more likely to choose a less attractive person at 4 pints of alcohol than females\n\n#### Results Section\n\n##### First write out the main effects\n\n> There was a significant main effect of the amount of alcohol consumed on the attractiveness of the date that was selected, F(2, 42) = 20.07, p \\< .001.\n\n> There was not a significant main effect of gender on the attractiveness of the date that was selected, F(1, 42) = 2.03, p = .161.\n\n##### Second, write out the interaction effect\n\n> There was a significant interaction effect between amount of alcohol consumed and gender on the attractiveness of the date that was selected F(2, 42) = 11.91, p \\< .001.\n\n##### Third, write out any relevant Tukey findings\n\n> TukeyHSD post hoc tests revealed that at the largest amount of alcohol consumption (4 pints) Males were significantly more likely to choose a less attractive date (M=35.6, SE=3.83) in comparison to females (M=57.5, SE=57.5). This difference, 21.88, 95% CI\\[8.27, 35.48\\] was significant with an adjusted p = .0003.\n",
    "supporting": [
      "Two-Way-ANOVA_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}