project:
  type: website
format:
  html:
    theme:
      light: minty
      dark: darkly
    css: styles.css
    toc: true
    link-external-newwindow: true
website:
  navbar:
    right: 
      - icon: github
        url: https://github.com/jvanster
    left:
      - text: "Online Resources"
        menu:
        - text: R for Data Science 2nd Ed
          url: https://r4ds.hadley.nz/
        - text: Scratch
          url: https://scratch.mit.edu/
        - text: Canvas LMS
          href: https://fresno.instructure.com/
    pinned: true
  title: "Using R Studio for Statistics"
  sidebar:
    style: "docked"
    background: primary
    search: true
    contents:
    - section: "R Basics"
      contents:
      - Why R.qmd
      - Intro to R.qmd
      - Building Databases.qmd
      - More with Databases.qmd
      - Working with Quarto.qmd
    - section: "Intro to Statistics"
      contents: 
        - Descriptive Statistics.qmd
        - Hypothesis_Testing.qmd
        - Probability Theory.qmd
        - Independent t test.qmd
        - Paired Samples t test.qmd
    - section: "Graphs"
      contents:
        - Intro to ggplot.qmd
        - Bar Graphs and CIs.qmd
        - Histograms.qmd
        - Normal Curve.qmd
    - section: "Statistical Tests"
      contents: 
        - Correlation.qmd
        - Regression.qmd
        - One-Way ANOVA.qmd
        - Two-Way ANOVA.qmd
        - ANCOVA.qmd
        - Chi Square.qmd




editor: visual


