<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="James Van Slyke" />


<title>Independent t test</title>

<script src="site_libs/header-attrs-2.10/header-attrs.js"></script>
<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/spacelab.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<script src="site_libs/clipboard-1.7.1/clipboard.min.js"></script>
<link href="site_libs/primer-tooltips-1.4.0/build.css" rel="stylesheet" />
<link href="site_libs/klippy-0.0.0.9500/css/klippy.min.css" rel="stylesheet" />
<script src="site_libs/klippy-0.0.0.9500/js/klippy.min.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>








<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Using R Studio for Statistics</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Basics
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="Why_R.html">Why Use R &amp; R Studio?</a>
    </li>
    <li>
      <a href="Intro_to_R.html">Intro to R</a>
    </li>
    <li>
      <a href="Building_databases.html">Building Databases</a>
    </li>
    <li>
      <a href="Descriptive_Statistics.html">Descriptive Statistics</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Graphs
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="Intro_ggplot.html">Intro to ggplot</a>
    </li>
    <li>
      <a href="Bar_Graphs_CI.html">Bar Graphs with 95% CIs</a>
    </li>
    <li>
      <a href="Histograms.html">Histograms</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Statistical Tests
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="Z_Test.html">One Sample z test</a>
    </li>
    <li>
      <a href="Independent_t-test.html">Independent t-test</a>
    </li>
    <li>
      <a href="Paired_samples_t-test.html">Paired Samples t-test</a>
    </li>
    <li>
      <a href="One_Way_ANOVA.html">One-Way ANOVA</a>
    </li>
    <li>
      <a href="Two_Way_ANOVA.html">Two-Way ANOVA</a>
    </li>
    <li>
      <a href="Chi_Square.html">Chi Square</a>
    </li>
    <li>
      <a href="Regression.html">Regression</a>
    </li>
    <li>
      <a href="Correlation.html">Correlation</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Independent t test</h1>
<h4 class="author">James Van Slyke</h4>

</div>


<script>
  addClassKlippyTo("pre.r, pre.markdown");
  addKlippy('left', 'top', 'auto', '1', 'Copy code', 'Copied!');
</script>
<p>Resources to consult Chapter 10 from Field, A. (2017). Discovering Statistics Using IBM SPSS Statistics (5th Edition). SAGE Publications, Ltd. (UK).</p>
<p>Section from <a href="https://learningstatisticswithr.com/book/ttest.html#studentttest">Learning Statistics with R</a></p>
<p>The independent t test is used when analyzing the difference in means between two separate groups. Typically, this is used to analyze the difference between the control group (group who did not receive the independent variable) and the experimental group (group who did receive the independent variable).</p>
<p>The null hypothesis assumes that the mean difference between the two groups is equal to zero. If the samples came from the same population, their means would be roughly the same and if they came from the same population their characteristics would be the same as well. Thus, the null hypothesis assumes no real differences based on the presence of the independent variable.</p>
<p>This type of design is sometimes referred as a <em>between-groups</em> or <em>independent</em> design. It requires a categorical (nominal) predictor or independent variable that will specify the two groups (experimental and control) and a continuous dependent variable that specifies the outcome.</p>
<p>There are two possible reasons why two samples have different means.</p>
<ol style="list-style-type: decimal">
<li>The two sample means come from the same population, but the existence of measurement error and variability are the reason they are different. (Null hypothesis)</li>
<li>The two sample means come from different populations, which have different characteristics, and reflect a genuine difference between the sample means. (Alternative hypothesis)</li>
</ol>
<p>The t test is related to the z test, except that we are analyzing t scores rather than z scores. Remember the formula for a z score. <span class="math display">\[
z = \frac{x - \mu}{\frac{\sigma}{\sqrt{n}}}
\]</span> So for the t test, we use a verion of the z test but compare the following: <span class="math display">\[
t = \frac{(observed \;difference\;between\;means) - (expected\; difference\; between\;means)}{estimate\; of\; the\; \;standard\; error\; of\; the\; differnce\; \\between\; two\; sample\; means}
\]</span> Remember that the null hypothesis assumes that the expected difference between the means is equal to zero. So the numerator will simply be the difference between the two sample means <span class="math inline">\(x_{1}-x_{2}\)</span>. The z test uses the standard deviation from the sample as an estimate of the error divided by the square root of n. The t distruiotn is slightly different. Instead, it uses the standard deviation from the <strong>sample</strong> as an estimate fo the standard error. However we need estimates from both sample 1 and sample 2 so the equation looks like this: <span class="math display">\[
\sqrt{\frac{s^{2}_{1}}{n_{1}}+\frac{s^{2}_{2}}{n_{2}} }
\]</span> This becomes the denominator of the independent t test formula, so we put it all together like this: <span class="math display">\[
t = \frac{x_{1}-x_{2}}{\sqrt{\frac{s^{2}_{1}}{n_{1}}+\frac{s^{2}_{2}}{n_{2}} }}
\]</span></p>
<p>##Independent t-test example</p>
<ol style="list-style-type: decimal">
<li>First Step, upload dataset from SPSS</li>
<li>Get data set named “Invisibility” from SPSS datasets</li>
<li>Use <em>import dataset</em> tool under the environment tab</li>
<li>Find file called <em>invisibility.sav</em></li>
</ol>
<pre class="r"><code>library(haven)
Invisibility &lt;- read_sav(&quot;Invisibility.sav&quot;)
View(Invisibility)</code></pre>
<p>Inspect variables</p>
<pre class="r"><code>Invisibility$Cloak</code></pre>
<pre><code>## &lt;labelled&lt;double&gt;[24]&gt;: Cloak of invisibility
##  [1] 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1
## 
## Labels:
##  value    label
##      0 No Cloak
##      1    Cloak</code></pre>
<pre class="r"><code>Invisibility$Mischief</code></pre>
<pre><code>##  [1] 3 1 5 4 6 4 6 2 0 5 4 5 4 3 6 6 8 5 5 4 2 5 7 5
## attr(,&quot;label&quot;)
## [1] &quot;Mischievous Acts&quot;
## attr(,&quot;format.spss&quot;)
## [1] &quot;F8.0&quot;</code></pre>
<p>Create bar graph to examine data First step is to create a dataset with your descriptive variables We’ll use the dplyr package to do this, which is part of tidyverse</p>
<pre class="r"><code>library(dplyr)
Invis_Descriptives &lt;- Invisibility %&gt;%
  group_by(Cloak) %&gt;%
  summarize(n = n(),
            mean = mean(Mischief),
            sd = sd(Mischief),
            se = sd / sqrt(n),
            ci = qt(0.975, df = n - 1) * sd / sqrt(n))
Invis_Descriptives</code></pre>
<pre><code>## # A tibble: 2 × 6
##          Cloak     n  mean    sd    se    ci
##      &lt;dbl+lbl&gt; &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 0 [No Cloak]    12  3.75  1.91 0.552  1.22
## 2 1 [Cloak]       12  5     1.65 0.477  1.05</code></pre>
<p>First let’s make a simple graph with just the basics</p>
<pre class="r"><code>ggplot(Invis_Descriptives, 
       aes(x = Cloak, 
           y = mean)) +
  geom_bar(stat = &quot;identity&quot;)</code></pre>
<pre><code>## Don&#39;t know how to automatically pick scale for object of type haven_labelled/vctrs_vctr/double. Defaulting to continuous.</code></pre>
<p><img src="Independent_t-test_files/figure-html/unnamed-chunk-4-1.png" width="672" /> Next let’s add error bars</p>
<pre class="r"><code>ggplot(Invis_Descriptives, 
       aes(x = Cloak, 
           y = mean)) +
  geom_bar(stat = &quot;identity&quot;) +
  geom_errorbar(aes(ymin=mean-ci,
                    ymax=mean+ci))</code></pre>
<pre><code>## Don&#39;t know how to automatically pick scale for object of type haven_labelled/vctrs_vctr/double. Defaulting to continuous.</code></pre>
<p><img src="Independent_t-test_files/figure-html/unnamed-chunk-5-1.png" width="672" /> We can add in labels to improve the look of our chart. We’ve added labels to our factor variable and labels for the title and x and y variables.</p>
<pre class="r"><code>ggplot(Invis_Descriptives, 
       aes(x = factor(Cloak, labels=c(&quot;No Cloak&quot;, &quot;Cloak&quot;)),
           y = mean)) +
  geom_bar(stat = &quot;identity&quot;) +
  geom_errorbar(aes(ymin=mean-ci,
                    ymax=mean+ci)) +
  labs(title = &quot;Mean Number of Mischievious Acts with or without Cloak&quot;, 
       y=&quot;Mean Number of Mischievious Acts&quot;, x=&quot;Were They Wearing a Cloak?&quot;)</code></pre>
<p><img src="Independent_t-test_files/figure-html/unnamed-chunk-6-1.png" width="672" /> Next let’s add some color to our chart</p>
<pre class="r"><code>ggplot(Invis_Descriptives, 
       aes(x = factor(Cloak, labels=c(&quot;No Cloak&quot;, &quot;Cloak&quot;)),
           y = mean)) +
  theme_minimal() +
  geom_bar(stat = &quot;identity&quot;, fill=&quot;cornflowerblue&quot;) +
  geom_errorbar(aes(ymin=mean-ci,
                    ymax=mean+ci), width=.3, size=1) +
  labs(title = &quot;Mean Number of Mischievious Acts with or without Cloak&quot;, 
       y=&quot;Mean Number of Mischievious Acts&quot;, x=&quot;Were They Wearing a Cloak?&quot;)</code></pre>
<p><img src="Independent_t-test_files/figure-html/unnamed-chunk-7-1.png" width="672" /> Based on the graph, it looks like there is a difference between the groups Let’s run a t test to make sure</p>
<pre class="r"><code>t.test(Mischief ~ Cloak, data = Invisibility)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  Mischief by Cloak
## t = -1.7135, df = 21.541, p-value = 0.101
## alternative hypothesis: true difference in means between group 0 and group 1 is not equal to 0
## 95 percent confidence interval:
##  -2.764798  0.264798
## sample estimates:
## mean in group 0 mean in group 1 
##            3.75            5.00</code></pre>
<p>List the effect size as well Cohen’s d - Subtract the means from each other and divide by the standard deviation of the control group</p>
<pre class="r"><code>Cohens_d &lt;- (5.00-3.75)/1.91
Cohens_d</code></pre>
<pre><code>## [1] 0.6544503</code></pre>
<p>Write out conclusion</p>
<p><em>On average, participants given a cloak of invisibility engaged in more acts of mischief (M = 5, SE = 0.48), than those not given a cloak (M = 3.75, SE = 0.55). This difference, 1.25, 95% CI[-2.76, 0.26], was not significant t(21.54) = −1.71, p = 0.101; however, it did represent a medium-sized effect d = 0.65.</em></p>
<p>Steps to writing results</p>
<ol style="list-style-type: decimal">
<li>Write out the means and include standard error</li>
<li>Write out the difference between the means (Subtract the sample means) and the confidence intervals for the difference</li>
<li>t(df)= t score, p value, Cohen’s d</li>
</ol>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
