<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="James Van Slyke" />


<title>Normal Curve and Z scores</title>

<script src="site_libs/header-attrs-2.14/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/darkly.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<script src="site_libs/clipboard-1.7.1/clipboard.min.js"></script>
<link href="site_libs/primer-tooltips-1.4.0/build.css" rel="stylesheet" />
<link href="site_libs/klippy-0.0.0.9500/css/klippy.min.css" rel="stylesheet" />
<script src="site_libs/klippy-0.0.0.9500/js/klippy.min.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Using R Studio for Statistics</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    R Basics
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="Why_R.html">Why Use R &amp; R Studio?</a>
    </li>
    <li>
      <a href="Intro_to_R.html">Intro to R</a>
    </li>
    <li>
      <a href="Building_databases.html">Building Databases</a>
    </li>
    <li>
      <a href="More_with_databases.html">More with Databases</a>
    </li>
    <li>
      <a href="Working_with_R_Markdown.html">Working with R Markdown</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Intro to Statistics
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="Descriptive_Statistics.html">Descriptive Statistics</a>
    </li>
    <li>
      <a href="Hypothesis_Testing.html">Hypothesis Testing</a>
    </li>
    <li>
      <a href="Probability_Theory.html">Probability Theory</a>
    </li>
    <li>
      <a href="Z_Test.html">z test</a>
    </li>
    <li>
      <a href="Independent_t-test.html">Independent t-test</a>
    </li>
    <li>
      <a href="Paired_samples_t-test.html">Paired Samples t-test</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Graphs
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="Intro_ggplot.html">Intro to ggplot</a>
    </li>
    <li>
      <a href="Bar_Graphs_CI.html">Bar Graphs with 95% CIs</a>
    </li>
    <li>
      <a href="Histograms.html">Histograms</a>
    </li>
    <li>
      <a href="Normal_Curve.html">Normal Curve</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Statistical Tests
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="Correlation.html">Correlation</a>
    </li>
    <li>
      <a href="Regression.html">Regression</a>
    </li>
    <li>
      <a href="One_Way_ANOVA.html">One-Way ANOVA</a>
    </li>
    <li>
      <a href="Two_Way_ANOVA.html">Two-Way ANOVA</a>
    </li>
    <li>
      <a href="Chi_Square.html">Chi Square</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Normal Curve and Z scores</h1>
<h4 class="author">James Van Slyke</h4>

</div>


<script>
  addClassKlippyTo("pre.r, pre.markdown");
  addKlippy('left', 'top', 'auto', '1', 'Copy code', 'Copied!');
</script>
<div id="properties-of-the-normal-curve" class="section level3">
<h3>Properties of the Normal Curve</h3>
<p>The normal curve is a special kind of histogram that has a particular
shape and certain properties. Remember that a histogram usually
represents a continuous variable, so it is most often numeric. There’s
other important attributes of the normal curve that are essential to
hypothesis testing and statistical analysis.</p>
<div class="figure">
<img
src="https://www.simplypsychology.org/normal-distribution.jpg?ezimgfmt=rs:555x353/rscb26/ng:webp/ngcb26"
alt="" />
<p class="caption">Normal Curve - <a
href="https://www.simplypsychology.org/normal-distribution.html"
class="uri">https://www.simplypsychology.org/normal-distribution.html</a></p>
</div>
<p>As described in the image above, there are several important
properties of a normal curve.</p>
<ol style="list-style-type: decimal">
<li><p>The distribution of scores is symmetrical about the mean, which
indicates that if you were to fold the distribution in half both sides
or tails of the distribution would match.</p></li>
<li><p>The mean, median and mode are all equal</p></li>
<li><p>The distribution will have two inflection points indicating one
standard deviation above and below the mean.</p></li>
</ol>
<p>Remember that in a normal curve most of the data is close to the mean
or scores with the highest frequency are closest to the mean. As you
move to the tails of the normal distribution there is a lower frequency
of scores, less of the variable is contained in the tails of the
distribution. Another way to think of this is that more extreme scores
(scores that are either much smaller or much larger than the mean) are
contained in the tails of the distribution and are less probable.</p>
</div>
<div
id="the-proportion-or-percentage-of-a-particular-variable-in-a-normal-curve-is-dispersed-differently-throughout-the-curve"
class="section level3">
<h3>The proportion or percentage of a particular variable in a normal
curve is dispersed differently throughout the curve</h3>
<div class="figure">
<img src="https://miro.medium.com/max/1400/1*IdGgdrY_n_9_YfkaCh-dag.png"
alt="" />
<p class="caption">Distribution of scores in a normal curve</p>
</div>
<p>Image credit - <a
href="https://towardsdatascience.com/understanding-the-68-95-99-7-rule-for-a-normal-distribution-b7b7cbf760c2"
class="uri">https://towardsdatascience.com/understanding-the-68-95-99-7-rule-for-a-normal-distribution-b7b7cbf760c2</a></p>
<ol style="list-style-type: decimal">
<li>34.13% of the data are between the mean and one standard deviation
above it or below it.</li>
<li>13.59% of the data is between one and two standard deviations</li>
<li>2.15% of the data is between two and three standard deviations</li>
</ol>
<p>So when a data point or score is further on either of the tails of
the distribution, the data point is less probable or more extreme.</p>
<div id="z-scores" class="section level4">
<h4>Z Scores</h4>
<p>One of the ways we are able to understand the probability or
distribution of scores in a normal curve is through the use of <em>z
scores</em>. A z score is score that designates how many standard
deviations a particular score is above or below the mean.</p>
<p>The formula is the score minus the mean divided by the standard
deviation. Here is the formula: <span class="math display">\[
z = \frac{X - \bar X}{s}
\]</span> z scores can be positive or negative depending on whether the
score in question is above or below the mean. Thus, the higher the
magnitude of the score (meaning independent of whether it’s positive or
negative) the further the score is away from the mean.</p>
<p><img
src="https://cdn.scribbr.com/wp-content/uploads/2020/10/standard-normal-distribution.png"
alt="Z scores" /> Image from <a
href="https://www.scribbr.com/statistics/standard-normal-distribution/"
class="uri">https://www.scribbr.com/statistics/standard-normal-distribution/</a></p>
<p>Each z score also has a particular percentage associated with it. So
for example we can see what percentage is associated with a z score of
1</p>
<pre class="r"><code>pnorm(1)</code></pre>
<pre><code>## [1] 0.8413447</code></pre>
<p>This tells us that a z score of 1 is at the 84th percentile or that
84% of the scores in a normal curve are below a z score of 1.</p>
<p>Remember also that half of the scores are above and below the mean or
50% of the scores are above and below the mean.</p>
<p>If we take this score (0.8413447) minus 50% or .50, we’ll get
proportion or percentage between the mean and 1 standard deviation above
it.</p>
<pre class="r"><code>pnorm(1) - .50</code></pre>
<pre><code>## [1] 0.3413447</code></pre>
<p>Notice that this is the same percentage we saw earlier between the
mean and one standard deviation above it, 34.13%.</p>
</div>
</div>
<div id="example-problem" class="section level3">
<h3>Example Problem</h3>
<p>Imagine that a nationwide mathematics aptitude test is normally
distributed with a mean of 80 and a standard deviation of 12. Here’s a
look at the graph of the distribution of mathematics aptitude test
scores.</p>
<p><img src="Normal_Curve_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<p>Now imagine our score on the aptitude test was 90 and we were curious
what percentage of scores were below our score. So we were interested in
the area below a score of 90 as shown in the shaded area below.</p>
<p><img src="Normal_Curve_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p>To perform this calculation, we can find the z score associated with
the score of 90 and then use <code>pnorm</code> to find what percentage
is associated with that z score.</p>
<p>Find the z score</p>
<pre class="r"><code>(90-84)/12</code></pre>
<pre><code>## [1] 0.5</code></pre>
<p>Then find the percentage associated with that z score</p>
<pre class="r"><code>pnorm(0.5)</code></pre>
<pre><code>## [1] 0.6914625</code></pre>
<p>So a score of 90 is at the 69th percentile or approximately 69% of
the scores on the aptitude test are less than a score of 90.</p>
<p>Or we can go the opposite direction. Let’s say we want to know the
percentage of scores above a score of 65. Or the area described
below.</p>
<p><img src="Normal_Curve_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p>First, we need to find the z score associated with a score of 65.</p>
<pre class="r"><code>(65-80)/12</code></pre>
<pre><code>## [1] -1.25</code></pre>
<p>Then we take the pnorm of that number but subtract it from 1.00
because we are looking for the scores above it.</p>
<pre class="r"><code>1.00 - pnorm(-1.25)</code></pre>
<pre><code>## [1] 0.8943502</code></pre>
<p>So approximately 89% of the scores are above a score of 65.</p>
<p>So if you want to know the percentage of scores above a particular
score you subtract the pnorm z score from 1.00, but if you want to know
the percentage below a certain number or the percentile rank, you simply
do the pnorm of the z score.</p>
<p>You can also find the percentage of scores between certain scores.
Just find the z scores associated with each score and subtract them.</p>
<p>For example, what percentage of scores are between a score of 72 and
106?</p>
<p><img src="Normal_Curve_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<p>Find the z score associated with each and then use pnorm to find the
percentage associated with each z score. Make sure to subtract the
smaller number from the larger.</p>
<pre class="r"><code>z1 &lt;- (72-80)/12
z2 &lt;- (106-80)/12
pnorm(z2) - pnorm(z1)</code></pre>
<pre><code>## [1] 0.7323773</code></pre>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
