<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="James Van Slyke" />


<title>One-Way ANOVA</title>

<script src="site_libs/header-attrs-2.11/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/darkly.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<script src="site_libs/clipboard-1.7.1/clipboard.min.js"></script>
<link href="site_libs/primer-tooltips-1.4.0/build.css" rel="stylesheet" />
<link href="site_libs/klippy-0.0.0.9500/css/klippy.min.css" rel="stylesheet" />
<script src="site_libs/klippy-0.0.0.9500/js/klippy.min.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>








<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Using R Studio for Statistics</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Basics
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="Why_R.html">Why Use R &amp; R Studio?</a>
    </li>
    <li>
      <a href="Intro_to_R.html">Intro to R</a>
    </li>
    <li>
      <a href="Building_databases.html">Building Databases</a>
    </li>
    <li>
      <a href="More_with_databases.html">More with Databases</a>
    </li>
    <li>
      <a href="Working_with_R_Markdown.html">Working with R Markdown</a>
    </li>
    <li>
      <a href="Descriptive_Statistics.html">Descriptive Statistics</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Graphs
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="Intro_ggplot.html">Intro to ggplot</a>
    </li>
    <li>
      <a href="Bar_Graphs_CI.html">Bar Graphs with 95% CIs</a>
    </li>
    <li>
      <a href="Histograms.html">Histograms</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Statistical Tests
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="Z_Test.html">One Sample z test</a>
    </li>
    <li>
      <a href="Independent_t-test.html">Independent t-test</a>
    </li>
    <li>
      <a href="Paired_samples_t-test.html">Paired Samples t-test</a>
    </li>
    <li>
      <a href="One_Way_ANOVA.html">One-Way ANOVA</a>
    </li>
    <li>
      <a href="Two_Way_ANOVA.html">Two-Way ANOVA</a>
    </li>
    <li>
      <a href="Chi_Square.html">Chi Square</a>
    </li>
    <li>
      <a href="Regression.html">Regression</a>
    </li>
    <li>
      <a href="Correlation.html">Correlation</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">One-Way ANOVA</h1>
<h4 class="author">James Van Slyke</h4>
<h4 class="date">3/29/2021</h4>

</div>


<script>
  addClassKlippyTo("pre.r, pre.markdown");
  addKlippy('left', 'top', 'auto', '1', 'Copy code', 'Copied!');
</script>
<pre><code>## Registered S3 method overwritten by &#39;psych&#39;:
##   method         from  
##   plot.residuals rmutil</code></pre>
<pre><code>## 
## Attaching package: &#39;psych&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:scales&#39;:
## 
##     alpha, rescale</code></pre>
<pre><code>## The following objects are masked from &#39;package:ggplot2&#39;:
## 
##     %+%, alpha</code></pre>
<p>One-Way ANOVA Example</p>
<p>Practice dataset: How does preschool affect language development?</p>
<p>Three groups that differ by how many hours they spent in preschool
per week</p>
<p>Variables</p>
<ul>
<li><p>IV = Preschool</p></li>
<li><p>DV = Language Development</p></li>
</ul>
<p>Language development was measured based on a language development
test score</p>
<p>Null Hypothesis: Attendance at preschool has no effect on language
development</p>
<p>View Dataset</p>
<pre class="r"><code>View(ch15ds1)</code></pre>
<p>View in R Console</p>
<pre class="r"><code>ch15ds1</code></pre>
<pre><code>##       Group Language.Score
## 1   5 Hours             87
## 2   5 Hours             86
## 3   5 Hours             76
## 4   5 Hours             56
## 5   5 Hours             78
## 6   5 Hours             98
## 7   5 Hours             77
## 8   5 Hours             66
## 9   5 Hours             75
## 10  5 Hours             67
## 11 10 Hours             87
## 12 10 Hours             85
## 13 10 Hours             99
## 14 10 Hours             85
## 15 10 Hours             79
## 16 10 Hours             81
## 17 10 Hours             82
## 18 10 Hours             78
## 19 10 Hours             85
## 20 10 Hours             91
## 21 20 Hours             89
## 22 20 Hours             91
## 23 20 Hours             96
## 24 20 Hours             87
## 25 20 Hours             89
## 26 20 Hours             90
## 27 20 Hours             89
## 28 20 Hours             96
## 29 20 Hours             96
## 30 20 Hours             93</code></pre>
<p>Let’s look at a bar graph of the data first</p>
<p>Step 1 - create table of Descriptive Statistics</p>
<pre class="r"><code>library(dplyr)
Preschool_Descriptives &lt;- ch15ds1 %&gt;%
  group_by(Group) %&gt;%
  summarize(n = n(),
            mean = mean(Language.Score),
            sd = sd(Language.Score),
            se = sd / sqrt(n),
            ci = qt(0.975, df = n - 1) * sd / sqrt(n))</code></pre>
<p>Check it out</p>
<pre class="r"><code>Preschool_Descriptives</code></pre>
<pre><code>## # A tibble: 3 × 6
##   Group        n  mean    sd    se    ci
##   &lt;chr&gt;    &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 10 Hours    10  85.2  6.20  1.96  4.43
## 2 20 Hours    10  91.6  3.41  1.08  2.44
## 3 5 Hours     10  76.6 12.0   3.78  8.56</code></pre>
<p>Now graph it based on the descriptive statistics</p>
<pre class="r"><code>ggplot(Preschool_Descriptives, 
       aes(x = Group, 
           y = mean)) +
  geom_bar(stat = &quot;identity&quot;) +
  geom_errorbar(aes(ymin=mean-ci,
                    ymax=mean+ci))</code></pre>
<p><img src="One_Way_ANOVA_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p>Run your ANOVA</p>
<p>First install Psych package</p>
<pre class="r"><code>library(psych)</code></pre>
<p>Check out the variables.</p>
<p>Psych package uses a different command for this “describeBy”</p>
<p>Must specify DV and groups</p>
<pre class="r"><code>describeBy(ch15ds1$Language.Score, group = ch15ds1$Group)</code></pre>
<pre><code>## 
##  Descriptive statistics by group 
## group: 10 Hours
##    vars  n mean  sd median trimmed  mad min max range skew kurtosis
## X1    1 10 85.2 6.2     85   84.38 5.19  78  99    21 0.89    -0.15
##      se
## X1 1.96
## --------------------------------------------------- 
## group: 20 Hours
##    vars  n mean   sd median trimmed  mad min max range skew
## X1    1 10 91.6 3.41   90.5   91.62 2.97  87  96     9 0.26
##    kurtosis   se
## X1    -1.72 1.08
## --------------------------------------------------- 
## group: 5 Hours
##    vars  n mean    sd median trimmed   mad min max range skew
## X1    1 10 76.6 11.96   76.5    76.5 14.08  56  98    42 0.05
##    kurtosis   se
## X1     -0.9 3.78</code></pre>
<p>Run your ANOVA! Something new, must save results in an object rather
than the results being there automatically</p>
<pre class="r"><code>m1 &lt;- aov(Language.Score~Group, data = ch15ds1)</code></pre>
<p>To get ANOVA table must use “summary” function</p>
<pre class="r"><code>summary(m1)</code></pre>
<pre><code>##             Df Sum Sq Mean Sq F value  Pr(&gt;F)   
## Group        2   1133   566.5   8.799 0.00114 **
## Residuals   27   1738    64.4                   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Figure out the effect size - Eta squared The formula is
SSbetween/SSTotal or SSbetween/SSbetween+SSResidual</p>
<pre class="r"><code>1133/(1133+1738)</code></pre>
<pre><code>## [1] 0.394636</code></pre>
<p>Write out conclusion</p>
<blockquote>
<p>Number of hours in Preschool had a significant effect on language
development, F(2, 27) = 8.799, p = 0.00114, 𝜂2 = 0.39.</p>
</blockquote>
<p>Where is the difference? Need to use post hoc tests</p>
<p>TukeyHSD will tell us where the differences are between the
individual groups.</p>
<p>Run TukeyHSD on saved ANOVA results</p>
<pre class="r"><code>TukeyHSD(m1)</code></pre>
<pre><code>##   Tukey multiple comparisons of means
##     95% family-wise confidence level
## 
## Fit: aov(formula = Language.Score ~ Group, data = ch15ds1)
## 
## $Group
##                    diff        lwr        upr     p adj
## 20 Hours-10 Hours   6.4  -2.497288 15.2972884 0.1941234
## 5 Hours-10 Hours   -8.6 -17.497288  0.2972884 0.0596448
## 5 Hours-20 Hours  -15.0 -23.897288 -6.1027116 0.0007780</code></pre>
<p>Finally, write out the whole conclusion.</p>
<blockquote>
<p>TukeyHSD post hoc tests revealed that 20 hours a week of preschool
(M=91.6, SE=1.96) resulted in significantly higher levels of language
development in comparison to 5 hours (M=76.6, SE=3.78). This difference,
-15 95% CI[-23.90, -6.10] was significant with an adjusted p =
.0008.</p>
</blockquote>
<p>Improve the graph</p>
<pre class="r"><code>ggplot(Preschool_Descriptives, 
       aes(x = Group, 
           y = mean)) +
  geom_bar(stat = &quot;identity&quot;) +
  geom_errorbar(aes(ymin=mean-ci,
                    ymax=mean+ci)) +
  scale_x_discrete(limits=c(&quot;5 Hours&quot;, &quot;10 Hours&quot;, &quot;20 Hours&quot;))</code></pre>
<p><img src="One_Way_ANOVA_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<p>Make it look real nice Clark</p>
<pre class="r"><code>ggplot(Preschool_Descriptives, 
       aes(x = Group,
           y = mean)) +
  theme_minimal() +
  geom_bar(stat = &quot;identity&quot;, fill=&quot;steelblue&quot;) +
  geom_errorbar(aes(ymin=mean-ci,
                    ymax=mean+ci), width=.3, size=1) +
  labs(title = &quot;Does Preschool Effect Language Development?&quot;, 
       y=&quot;Mean Score on Language Test&quot;, x=&quot;Number of Hours Spent in Preschool&quot;) +
  scale_x_discrete(limits=c(&quot;5 Hours&quot;, &quot;10 Hours&quot;, &quot;20 Hours&quot;))</code></pre>
<p><img src="One_Way_ANOVA_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
