<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="James Van Slyke" />


<title>Paired samples t-test</title>

<script src="site_libs/header-attrs-2.14/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/darkly.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<script src="site_libs/clipboard-1.7.1/clipboard.min.js"></script>
<link href="site_libs/primer-tooltips-1.4.0/build.css" rel="stylesheet" />
<link href="site_libs/klippy-0.0.0.9500/css/klippy.min.css" rel="stylesheet" />
<script src="site_libs/klippy-0.0.0.9500/js/klippy.min.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Using R Studio for Statistics</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    R Basics
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="Why_R.html">Why Use R &amp; R Studio?</a>
    </li>
    <li>
      <a href="Intro_to_R.html">Intro to R</a>
    </li>
    <li>
      <a href="Building_databases.html">Building Databases</a>
    </li>
    <li>
      <a href="More_with_databases.html">More with Databases</a>
    </li>
    <li>
      <a href="Working_with_R_Markdown.html">Working with R Markdown</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Intro to Statistics
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="Descriptive_Statistics.html">Descriptive Statistics</a>
    </li>
    <li>
      <a href="Hypothesis_Testing.html">Hypothesis Testing</a>
    </li>
    <li>
      <a href="Probability_Theory.html">Probability Theory</a>
    </li>
    <li>
      <a href="Z_Test.html">z test</a>
    </li>
    <li>
      <a href="Independent_t-test.html">Independent t-test</a>
    </li>
    <li>
      <a href="Paired_samples_t-test.html">Paired Samples t-test</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Graphs
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="Intro_ggplot.html">Intro to ggplot</a>
    </li>
    <li>
      <a href="Bar_Graphs_CI.html">Bar Graphs with 95% CIs</a>
    </li>
    <li>
      <a href="Histograms.html">Histograms</a>
    </li>
    <li>
      <a href="Normal_Curve.html">Normal Curve</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Statistical Tests
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="Correlation.html">Correlation</a>
    </li>
    <li>
      <a href="Regression.html">Regression</a>
    </li>
    <li>
      <a href="One_Way_ANOVA.html">One-Way ANOVA</a>
    </li>
    <li>
      <a href="Two_Way_ANOVA.html">Two-Way ANOVA</a>
    </li>
    <li>
      <a href="Chi_Square.html">Chi Square</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Paired samples t-test</h1>
<h4 class="author">James Van Slyke</h4>
<h4 class="date">3/29/2021</h4>

</div>


<script>
  addClassKlippyTo("pre.r, pre.markdown");
  addKlippy('left', 'top', 'auto', '1', 'Copy code', 'Copied!');
</script>
<p>####Paired samples t-test</p>
<p>*Make sure to read the description of the independent t test before
moving to the paired t-test</p>
<p>Here’s two books that would be good to reference for this discussion.
- Chapter 10 from Field, A. (2017). <em>Discovering Statistics Using IBM
SPSS Statistics</em> (5th Edition). SAGE Publications, Ltd. (UK). -
Chapter 13 &amp; 14 from Pagano, R. (2010). <em>Understanding Statistics
in the Behavioral Sciences</em> (9th Edition). Wadsworth.</p>
<p>The paired samples t-test is very similar to the independent t-test
and the basic assumptions regarding the the two groups are the same.</p>
<blockquote>
<p>Null Hypothesis - Experimental Group = Control Group</p>
</blockquote>
<blockquote>
<p>Alternative Hypothesis - Experimental Group <span
class="math inline">\(\neq\)</span> Control Group</p>
</blockquote>
<p>The difference in the paired samples t-test is that a single group
goes through both the experimental and control conditions. The control
condition is sometime referred to as the <em>baseline</em>, it’s the
measurement of a dependent variable without the presence of the
independent variable.</p>
<p>For example, assume you are testing the effectiveness of a new drug
on treating depression. You measure the current level of a sample of
persons who are currently experiencing depression (baseline) then allow
them to take the new drug for a month and then measure their depression
a second time. So the assumptions of our two hypotheses would look
something like this:</p>
<blockquote>
<p>Null Hypothesis - Before taking the drug = After taking the drug</p>
</blockquote>
<blockquote>
<p>Alternative Hypothesis - Before taking the drug <span
class="math inline">\(\neq\)</span> After taking the drug</p>
</blockquote>
<p>The equation is similar to the equation for the z test.</p>
<p><span class="math display">\[
z = \frac{x - \mu}{\frac{\sigma}{\sqrt{n}}}
\]</span></p>
<p>Remember that the z test really boils down to the difference between
the population mean and the sample mean divided by the standard
error.</p>
<p>Let’s look at the formula and then we can break down the
elements.</p>
<p><span class="math display">\[
t = \frac{\bar D - \mu_{D}}{\frac{s_{D}}{\sqrt{n}}}
\]</span> The first element is the mean of the difference scores <span
class="math inline">\(\bar D\)</span>. The t test calculates the
difference between each subject before and then after the introduction
of the independent variable. For our example, it would be the difference
in their level of depression before and after taking the new drug. AFter
all the differences are calculated the mean difference is found <span
class="math inline">\(\bar D\)</span>. Obviously, if the independent
variable has an effect, this number should have some amount of
magnitude.</p>
<p>The second element to look at is the mean of the population for
difference scores assuming the null hypothesis is true <span
class="math inline">\(\mu_{D}\)</span>. Remember that the Null
hypothesis assumes no difference between the sample means, so it assumes
that this sample of differences scores comes from a population with zero
different or has a mean value of 0.</p>
<p><span class="math display">\[
\mu_{D}=0
\]</span></p>
<p>Since this value is zero, it basically falls out of the equation, but
it does remind us of the basis for this kind of t test. The comparison
in the formula is between a sample and a population as we saw in the z
test. However, in this cases it’s a sample of difference scores compared
to a population of difference scores with an assumed mean of zero as
noted in the equation above, so the hypotheses have these
assumptions.</p>
<blockquote>
<p>Null Hypothesis - The sample can reasonably be said to have come from
a popultion of differnce scores with a mean of zero. Any difference
between the means is the result of measurement error</p>
</blockquote>
<blockquote>
<p>Alternative Hypothesis - The sample <em>can not</em> reasonably be
said to have come from a population of difference scores with a mean of
zero because the difference is too great and not the result of
measurement error.</p>
</blockquote>
<p>As before with the z test, we need some kind of value to compare to
the mean difference. In this case, as with the z test, the comparison is
to the error. More specifically to the measurement error that could
reasonably be expected based on random variation. This value is known as
the standard error of the differences. This standard error is an
indicator of the size of potential differences in sample means based on
sampling variation.</p>
<p>Here’s the formula/symbols <span class="math display">\[
\frac{s_{D}}{\sqrt{n}}
\]</span></p>
<p>If you look closely, this formula looks remarkably similar to the
standard error of the mean (because it is!) but notice how the standard
deviation from the population <span
class="math inline">\(\sigma\)</span> has been replaced with the
standard deviation from the sample <span
class="math inline">\(s\)</span>. What is unique about the standard
error of the differences is that it uses the standard deviation from the
sample as an <em>estimate</em> of the standard deviation from the
population.</p>
<p>Once the t score is found using the formula, it is compared to the t
distribution, which is very similar to the z distribution.</p>
<blockquote>
<p>The sampling distribution of t is a probability distribution of t
values that would occur if all possible different samples of a fixed
size N were drawn from the null hypothesis population (Pagano,
p. 320)</p>
</blockquote>
<p>The t distribution varies based on the degrees of freedom, which is
directly related to N. Just the the z distribution, the t distribution
has a mean of zero and as t values get larger, they are situated on the
tails of the distribution as either positive or negative numbers. Just
like with z scores, the larger the t score the less likely the sample of
obtained difference scores can reasonably be assumed to have come from a
population of differnce scores with a mean of zero.</p>
<p>For the example import the following dataset.</p>
<pre class="r"><code>ch14ds1 &lt;- read.csv(&quot;ch14ds1.csv&quot;)</code></pre>
<p>Check out dataset</p>
<pre class="r"><code>View(ch14ds1)</code></pre>
<p>View in Console</p>
<pre class="r"><code>ch14ds1</code></pre>
<pre><code>##    Pretest Posttest
## 1        3        7
## 2        5        8
## 3        4        6
## 4        6        7
## 5        5        8
## 6        5        9
## 7        4        6
## 8        5        6
## 9        3        7
## 10       6        8
## 11       7        8
## 12       8        7
## 13       7        9
## 14       6       10
## 15       7        9
## 16       8        9
## 17       8        8
## 18       9        8
## 19       9        4
## 20       8        4
## 21       7        5
## 22       7        6
## 23       6        9
## 24       7        8
## 25       8       12</code></pre>
<p>Notice that this is a fairly straightforward pre vs. posttest
dataset.</p>
<p>Use the summary command to look at the descriptive statistics</p>
<pre class="r"><code>summary(ch14ds1)</code></pre>
<pre><code>##     Pretest        Posttest    
##  Min.   :3.00   Min.   : 4.00  
##  1st Qu.:5.00   1st Qu.: 6.00  
##  Median :7.00   Median : 8.00  
##  Mean   :6.32   Mean   : 7.52  
##  3rd Qu.:8.00   3rd Qu.: 9.00  
##  Max.   :9.00   Max.   :12.00</code></pre>
<p>The means between the two groups are different and we can calculate
the difference.</p>
<pre class="r"><code>7.52-6.32</code></pre>
<pre><code>## [1] 1.2</code></pre>
<p>Of course, we need to determine whether this difference is
significant or not. So let’s use r to run the paired samples t test.
Notice that the code is fairly straightforward. Start with the
<em>t.test</em> command and then list the two variables that are being
analyzed, followed by lettting R know you want to perform a paired test
<em>paired = TRUE</em>.</p>
<pre class="r"><code>t.test(ch14ds1$Posttest, ch14ds1$Pretest, paired = TRUE)</code></pre>
<pre><code>## 
##  Paired t-test
## 
## data:  ch14ds1$Posttest and ch14ds1$Pretest
## t = 2.4495, df = 24, p-value = 0.02198
## alternative hypothesis: true mean difference is not equal to 0
## 95 percent confidence interval:
##  0.1889003 2.2110997
## sample estimates:
## mean difference 
##             1.2</code></pre>
<p>Based on the results, there does appear to be a significant
difference between the pre and post tests.</p>
<p>List the effect size as well using Cohen’s d - Subtract the means
from each other and divide by the standard deviation of the control
group</p>
<pre class="r"><code>Cohens_d &lt;- (7.52-6.32)/1.73
Cohens_d</code></pre>
<pre><code>## [1] 0.6936416</code></pre>
<div id="bar-graph" class="section level4">
<h4>Bar Graph</h4>
<p>This time let’s use a ggplot to make a better looking bar graph.
Check out the format of the data</p>
<pre class="r"><code>ch14ds1</code></pre>
<pre><code>##    Pretest Posttest
## 1        3        7
## 2        5        8
## 3        4        6
## 4        6        7
## 5        5        8
## 6        5        9
## 7        4        6
## 8        5        6
## 9        3        7
## 10       6        8
## 11       7        8
## 12       8        7
## 13       7        9
## 14       6       10
## 15       7        9
## 16       8        9
## 17       8        8
## 18       9        8
## 19       9        4
## 20       8        4
## 21       7        5
## 22       7        6
## 23       6        9
## 24       7        8
## 25       8       12</code></pre>
<p>The data is set up for a paired t test, so it includes 2 numeric
variables. This is a problem because a single factor variable is missing
that would be used to describe our two bars (i.e. pre and post
test).</p>
<p>Thus, we need to create a second dataset or dataframe that has a
factor variable (“Group”) and numeric (“Test”) variable. A new object is
created called “TestData”. The factor variable is created from scratch
using the “rep” repeat function and then adding together the Pre and
Post Test scores into a single numeric variable.</p>
<pre class="r"><code>TestData &lt;- data.frame(
            group= rep(c(&quot;Pretest&quot;, &quot;Posttest&quot;), each=25),
            Test = c(ch14ds1$Pretest, ch14ds1$Posttest)
            )</code></pre>
<p>Next, find the descriptive statistics for this new dataset</p>
<pre class="r"><code>library(dplyr)
Test_Descriptives &lt;- TestData %&gt;%
  group_by(group) %&gt;%
  summarize(n = n(),
            mean = mean(Test),
            sd = sd(Test),
            se = sd / sqrt(n),
            ci = qt(0.975, df = n - 1) * sd / sqrt(n))</code></pre>
<p>Check the descriptives and make sure they turned out ok.</p>
<pre class="r"><code>Test_Descriptives</code></pre>
<pre><code>## # A tibble: 2 × 6
##   group        n  mean    sd    se    ci
##   &lt;chr&gt;    &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 Posttest    25  7.52  1.83 0.366 0.755
## 2 Pretest     25  6.32  1.73 0.345 0.712</code></pre>
<p>Finally, create a basic bar graph</p>
<pre class="r"><code>ggplot(Test_Descriptives, 
       aes(x = group, 
           y = mean)) +
  geom_bar(stat = &quot;identity&quot;)</code></pre>
<p><img src="Paired_samples_t-test_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<p>Then let’s add in some error bars with the <em>geom_errorbar</em>
function.</p>
<pre class="r"><code>ggplot(Test_Descriptives, 
       aes(x = group, 
           y = mean)) +
  geom_bar(stat = &quot;identity&quot;) +
  geom_errorbar(aes(ymin=mean-ci,
                    ymax=mean+ci))</code></pre>
<p><img src="Paired_samples_t-test_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<p>Finally, let’s make it look really nice</p>
<pre class="r"><code>ggplot(Test_Descriptives, 
       aes(x = group,
           y = mean)) +
  theme_minimal() +
  geom_bar(stat = &quot;identity&quot;, fill=&quot;cornflowerblue&quot;) +
  geom_errorbar(aes(ymin=mean-ci,
                    ymax=mean+ci), width=.3, size=1) +
  labs(title = &quot;Change in Performance from Pre to Post Tests&quot;, 
       y=&quot;Mean Score&quot;, x=&quot;Tests&quot;)</code></pre>
<p><img src="Paired_samples_t-test_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<p>You can also flip the columns to make it look cleaner</p>
<pre class="r"><code>ggplot(Test_Descriptives, 
       aes(x = group,
           y = mean)) +
  theme_minimal() +
  geom_bar(stat = &quot;identity&quot;, fill=&quot;cornflowerblue&quot;) +
  geom_errorbar(aes(ymin=mean-ci,
                    ymax=mean+ci), width=.3, size=1) +
  labs(title = &quot;Change in Performance from Pre to Post Tests&quot;, 
       y=&quot;Mean Score&quot;, x=&quot;Tests&quot;) +
  scale_x_discrete(limits=c(&quot;Pretest&quot;, &quot;Posttest&quot;))</code></pre>
<p><img src="Paired_samples_t-test_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<p>Finally, we can write out the results, which is essentially the same
format as the independent t test.</p>
<blockquote>
<p>On average, scores on the posttest were larger (M = 7.52, SE = .37)
than the scores on the pretest (M = 6.32, SE = .35). This difference,
1.2, 95% CI[.19, 2.21], was significant t(24) = 2.45, p = 0.02. The
results represented an effect size of d = 0.69.*</p>
</blockquote>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
