{
  "hash": "b673b13a1b59b3f7a58bd00e2f8d44c7",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"ANCOVA\"\nauthor: \"James Van Slyke\"\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.1.4     ✔ readr     2.1.5\n✔ forcats   1.0.0     ✔ stringr   1.5.1\n✔ ggplot2   3.5.1     ✔ tibble    3.2.1\n✔ lubridate 1.9.3     ✔ tidyr     1.3.1\n✔ purrr     1.0.2     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(car)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: carData\n\nAttaching package: 'car'\n\nThe following object is masked from 'package:dplyr':\n\n    recode\n\nThe following object is masked from 'package:purrr':\n\n    some\n```\n\n\n:::\n:::\n\n\n### Analysis of *Co*variance\n\nThe ANOVA allows us to analyze the effect of various levels of an independent variable on the dependent variable. The *t* test is used for two groups that vary based on the presence of an independent variable, but the ANOVA allows us to look at 3 or more groups. The ANCOVA is used when analyzing levels of an independent variable adjusted based on the expected effect of another *second* variable (Field).\n\nIn this case, the second variable is typically a continuous variable and usually functions as a type of pre-existing condition. So the second variable is *not* something manipulated in the experiment, but still thought to effect the relationship between the independent and dependent variable. This second variable is called a *covariate*.\n\n### ANOVA Review\n\nRemember that the ANOVA or F statistic is based on comparing the explained variance or variance we can attribute to the manipulation of the independent variable to the unexplained variance or variance attributed to measurement error. So the basic comparison is between the variation between the groups compared to the variation within the groups.\n\n$$\n\\frac{SS_{between}}{SS_{within}}\n$$ However it takes a few more steps to get to the F value base on the mean squares $MS$, so the full formula looks like this: $$\n\\frac{SS_{between}/df_{between}}{SS_{within}/df_{within}} = \\frac{MS_{between}}{MS_{within}}= F\n$$\n\n#### ANOVA in R Studio\n\nWhen performing ANOVA in R Studio, we use the general linear model, which is highly related to ANOVA, so the basic formula in R Studio looks like this with $M$ standing for Model and $R$ standing for residuals:\n\n$$\n\\frac{SS_{M}}{SS_{R}}\n$$\n\n### Confounds\n\nOne of the primary issues in experimental design is confounds. Confounds are other variables (sometimes called nuisance variables) besides the independent variable that have an effect on the dependent variable. So a lot of work in experimental design is trying to control for or eliminate confounds, which is why experimental psychologists work so hard to try and have everything the same in the control and experimental conditions, except for the manipulation of the independent variable.\n\n### Reducing Error Variance\n\nThe ANCOVA tries to account for other potential confounds by *reducing* the within groups error variance $SS_R$. $SS_R$ is variance that is *unexplained*. So if part of that unexplained variance can be accounted for by another variable (the covariate) it increases the likelihood of detecting a real effect of the independent variable.\n\nThe covariate is typically a variable that effects the relationship between the independent variable and the dependent variable, but is not likely to be something that could be manipulated in an experiment. This is often because it is something that is a pre-existing condition or a variable that develops in individuals participants over time.\n\n### Revisiting Some Mischief\n\nFor the section on the independent t test, we looked at the effect of an invisibility cloak on acts of mischief. The idea was that if you had an invisibility cloak (like the one used by Harry Potter to explore Hogwarts) you might be more inclined to do more types of mischief.\n\nHowever, a potential covariate would be how mischievous you are more generally. So if you are already someone who is always getting into trouble (pulling pranks, being sent to the principal's office, often serving detention, etc), you are already more likely to do a lot of mischief before you get access to an invisibility cloak. So an ANCOVA allows for a participant's previous mischief to be accounted for when exploring the relationship between the primary relationship between the invisibility cloak and mischief. This would help to separate the influence of being mischievous more generally from the effect of the invisibility cloak on mischievous behavior.\n\nHere's a look at the data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(haven)\nInvisibility_Baseline <- read_sav(\"Invisibility Baseline.sav\")\nInvisibility_Baseline\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 80 × 3\n   cloak        mischief1 mischief2\n   <dbl+lbl>        <dbl>     <dbl>\n 1 0 [No Cloak]         4        11\n 2 0 [No Cloak]         5         7\n 3 0 [No Cloak]         8         8\n 4 0 [No Cloak]         6         7\n 5 0 [No Cloak]         6        10\n 6 0 [No Cloak]         4         7\n 7 0 [No Cloak]         3        11\n 8 0 [No Cloak]         6         7\n 9 0 [No Cloak]         7        11\n10 0 [No Cloak]         1         6\n# ℹ 70 more rows\n```\n\n\n:::\n:::\n\n\nIn this case, `mischief1` is the baseline level of mischief or how often a subject engages in mischievous acts on a regular basis. Baseline data is used in a lot of different situations to refer to how persons perform on a variable in everyday situations. So you might think about a baseline heart rate or a baseline level of religiosity. So prior to any experimental manipulation, baseline gives you the current level of some measure of a variable.\n\n### An Example with Puppies\n\nLet's look at an example using puppies or more specifically using puppies as a form of therapy (Field). Here's the dataset.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(haven)\nPuppy_love <- read_sav(\"Puppy Love.sav\")\nPuppy_love\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 30 × 4\n   Person Dose        Happiness Puppy_love\n    <dbl> <dbl+lbl>       <dbl>      <dbl>\n 1      1 1 [Control]         3          4\n 2      2 1 [Control]         2          1\n 3      3 1 [Control]         5          5\n 4      4 1 [Control]         2          1\n 5      5 1 [Control]         2          2\n 6      6 1 [Control]         2          2\n 7      7 1 [Control]         7          7\n 8      8 1 [Control]         2          4\n 9      9 1 [Control]         4          5\n10     10 2 [15 mins]         7          5\n# ℹ 20 more rows\n```\n\n\n:::\n:::\n\n\nThe independent variable is `Dose`. There are three levels to the independent variable (Control, 15 mins, and 30 mins), which refers to the amount of time spent with the puppies.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nPuppy_love$Dose\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n<labelled<double>[30]>: Dose of puppies\n [1] 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 3 3 3\n\nLabels:\n value   label\n     1 Control\n     2 15 mins\n     3 30 mins\n```\n\n\n:::\n:::\n\n\nThe dependent variable would be `Happiness`, which refers to the amount of happiness participants experienced after spending time with the puppies, which is on a 0-10 point scale.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nPuppy_love$Happiness\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] 3 2 5 2 2 2 7 2 4 7 5 3 4 4 7 5 4 9 2 6 3 4 4 4 6 4 6 2 8 5\nattr(,\"label\")\n[1] \"Happiness (0-10)\"\nattr(,\"format.spss\")\n[1] \"F8.0\"\nattr(,\"display_width\")\n[1] 11\n```\n\n\n:::\n:::\n\n\nSo, the primary hypotheses would be:\n\nNull - Puppy therapy has no effect on happiness\n\nAlternative - Puppy therapy has an effect on happiness\n\nAs before, the first step will be to turn Dose into a factor to better show the levels of the independent variable. This time we'll use the tidyverse to modify this type of variable\n\n\n::: {.cell}\n\n```{.r .cell-code}\nPuppy_love <- Puppy_love |> \n  mutate(Dose = factor(Dose, levels = c(1, 2, 3), \n         labels = c(\"Control\", \"15 mins\", \"30 mins\")))\n```\n:::\n\n\nTo begin, look at the mean difference of happiness based on the condition of puppy therapy.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nPuppy_love |> \n  group_by(Dose) |>\n    summarize(n = n(),\n              mean = mean(Happiness))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  Dose        n  mean\n  <fct>   <int> <dbl>\n1 Control     9  3.22\n2 15 mins     8  4.88\n3 30 mins    13  4.85\n```\n\n\n:::\n:::\n\n\nNotice that there is no real difference between 15 mins and 30 mins of puppy therapy, but there is a difference between the control group and both 15 and 30 mins of puppy therapy. Next, we'll need to run the ANOVA to decide if this mean difference is significant or not.\n\n### Puppy Love ANOVA\n\nTo run the ANOVA we need to use the `aov` argument and save it as an object.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nPuppy_ANOVA <- aov(Happiness ~ Dose, data = Puppy_love)\n```\n:::\n\n\nOnce the ANOVA has been saved, we can look at the results\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(Puppy_ANOVA)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Df Sum Sq Mean Sq F value Pr(>F)\nDose         2  16.84   8.422   2.416  0.108\nResiduals   27  94.12   3.486               \n```\n\n\n:::\n:::\n\n\nNotice that the F value is not significant. It's only 2.416 with a p value of 0.1008. So on the face of it, it would appear that Puppy therapy doesn't have an effect on happiness. This is where looking at the influence of a covariate might be helpful. The ability for puppy therapy to have an effect on your level of happiness would certainly be related to whether or not you liked puppies in the first place! Perhaps you are not a dog lover or you've had negative experiences with dogs. If we can account for the influence of this covariate, it may help us to see if puppy therapy actually has an effect on happiness.\n\nIn the dataset, the covariate is lised as `Puppy_love` and is based on a 0 to 7 scale.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nPuppy_love$Puppy_love\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] 4 1 5 1 2 2 7 4 5 5 3 1 2 2 6 4 2 1 3 5 4 3 3 2 0 1 3 0 1 0\nattr(,\"label\")\n[1] \"Love of puppies (0-7)\"\nattr(,\"format.spss\")\n[1] \"F8.0\"\nattr(,\"display_width\")\n[1] 12\n```\n\n\n:::\n:::\n\n\nThe code for this model is changed slightly to account for the covariate, `Puppy_love`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nPuppy_ANCOVA <- aov(Happiness ~ Dose + Puppy_love, data = Puppy_love)\n```\n:::\n\n\nTo look at the results we have to use a slightly different version of ANOVA (\"type = III\") using the car package. So this is what the summary looks like\n\n\n::: {.cell}\n\n```{.r .cell-code}\nAnova(Puppy_ANCOVA, type = \"III\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnova Table (Type III tests)\n\nResponse: Happiness\n            Sum Sq Df F value  Pr(>F)  \n(Intercept) 12.943  1  4.2572 0.04920 *\nDose        25.185  2  4.1419 0.02745 *\nPuppy_love  15.076  1  4.9587 0.03483 *\nResiduals   79.047 26                  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nThe first thing to notice here is that the variable Dose is now significant with an F value of 4.1419 and a p value of 0.02745. Puppy_love is also significant with an F value of 4.9587 and a p value of 0.03483.\n\nIf you look back at the original ANOVA, the residual sum of squares is 94.12. Notice that here the residual sum of squares is 79.047, so the inclusion of the co-variate has *reduced* the residual sum of squares. It's important to note that the total sum of squares or total variance has not changed, but how that variance has been accounted for has changed, which changes the overall results.\n\n### Effect size for ANCOVA\n\nThe effect size for ANCOVA uses something slightly different then the eta squared $\\eta^2$ we used for the ANOVA called a *partial* eta squared. It is a proportion of variance that a variable explains in comparison to the variance not explained by other variables. Here is the formula.\n\n$$\n\\frac{SS_{effect}}{SS_{effect}+SS_{residual}}\n$$\n\nSo you look at the sum of squares for the effect of interest (in this case, either the independent variable or covariate) then divide by that same effect plus the residual. Here is the formula for the independent variable Dose.\n\n$$\nDose=\\frac{25.185}{25.185+79.047}\n$$\n\nIn R Studio\n\n\n::: {.cell}\n\n```{.r .cell-code}\n25.185/(25.185+79.047)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.2416245\n```\n\n\n:::\n:::\n\n\nAnd then the formula for the covariate Puppy_love\n\n$$\nPuppy_love=\\frac{15.076}{15.076+79.047}\n$$\n\nIn R Studio\n\n\n::: {.cell}\n\n```{.r .cell-code}\n15.076/(15.076+79.047)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1601734\n```\n\n\n:::\n:::\n\n\nSo writing out the results looks like this:\n\n> The covariate, love of puppies, was significantly related to the participant's happiness, *F*(1, 26) = 4.96, *p* = 0.035, partial $\\eta^2$ =0.16. There was also a significant effect of puppy therapy on levels of happiness after controlling for the effect of love of puppies, *F*(2, 26) = 4.14, *p* = 0.027, partial $\\eta^2$ = 0.24.\n\n## Graphing the results\n\nFor graphing the results, a bar graph is the best way to look at the means. We can use the same basic formula we used for the one way anova to find our descriptive statistics.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nANCOVA_Descriptives <- Puppy_love |>\n  group_by(Dose) |>\n  summarize(n = n(),\n            mean = mean(Happiness),\n            sd = sd(Happiness),\n            se = sd / sqrt(n),\n            ci = qt(0.975, df = n - 1) * sd / sqrt(n))\n```\n:::\n\n\nAnd then create the graph\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(ANCOVA_Descriptives, \n       aes(x = Dose, \n           y = mean)) +\n  geom_bar(stat = \"identity\") +\n  geom_errorbar(aes(ymin=mean-ci,\n                    ymax=mean+ci))\n```\n\n::: {.cell-output-display}\n![](ANCOVA_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\nOf course, it's better to improve the graph a bit.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(ANCOVA_Descriptives, \n       aes(x = Dose,\n           y = mean)) +\n  theme_minimal() +\n  geom_bar(stat = \"identity\", fill=\"steelblue\") +\n  geom_errorbar(aes(ymin=mean-ci,\n                    ymax=mean+ci), width=.3, size=1) +\n  labs(title = \"Does Puppy Therapy Effect Happiness?\", \n       y=\"Mean Level of Happiness\", x=\"Time Spent in Puppy Therapy\") \n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.\nℹ Please use `linewidth` instead.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](ANCOVA_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n",
    "supporting": [
      "ANCOVA_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}